[project]
name = "llms-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.4.0",
    "datasets>=3.0.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "openai>=2.7.2",
    "python-dotenv>=1.2.1",
    "tensorflow==2.15.0",
    "tiktoken>=0.12.0",
    "transformers>=4.56.1",
    "trl",
]

[project.optional-dependencies]
bco = [
    "scikit-learn",
    "joblib"
]
deepspeed = [
    "deepspeed>=0.14.4"
]
judges = [
    "openai>=1.23.2",
    "llm-blender>=0.0.2"
]
liger = [
    "liger-kernel>=0.6.2"
]
peft = [
    "peft>=0.8.0"
]
quantization = [
    "bitsandbytes"
]
scikit = [
    "scikit-learn"
]
vllm = [
    "vllm==0.10.2",
    "fastapi",
    "pydantic",
    "requests",
    "uvicorn"
]
vlm = [
    "Pillow",
    "torchvision",
    "num2words==0.5.14"
]
math_verify = [
    "math-verify>=0.5.2",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
trl = { git = "https://github.com/huggingface/trl.git", rev = "v0.25.0" }
